Proyecto/Veterianimal/Veterianimal/Veterianimal/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from rating.views import rating
from products.views import ProductListView, IndexListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('contact/', views.contact, name='contact'),
    path('', IndexListView.as_view(), name='index'),
    path('users/rating/', rating, name='rating'),
    path('products/product/', ProductListView.as_view(), name='product'),
    path('users/product_history', views.product_history, name='history_product'),
    path('users/page-user/', views.user, name='user'),
    path('users/register/', views.registrar_usuario, name='registrar'),
    path('cart/', include('carts.urls')),
    path('product-detail/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls'))
]#llaves

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

Proyecto/Veterianimal/Veterianimal/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion/', views.address, name='address'),
    path('sleccionar/direccion/', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion/', views.confirm, name='confirm'),
    path('cancelar/', views.cancel, name='cancel'),
    path('completar/', views.complete, name='complete'),
    path('completados/', views.OrderListView.as_view(), name='completeds')
]

Proyecto/Veterianimal/Veterianimal/shipping_addresses/urls.py
from stat import S_ENFMT
from django.urls import path

from . import views

app_name = "shipping_addresses"

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateview.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteview.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

Proyecto/Veterianimal/Veterianimal/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<pk:slug>/', views.UserDetailView.as_view(), name='user'), 
]

Proyecto/Veterianimal/Veterianimal/orders/models.py
from django.db import models
from enum import Enum
import uuid
from django.db.models.signals import pre_save
from user.models import User_web
from carts.models import Cart
from shipping_addresses.models import ShippingAddress

from .common import OrderStatus
from .common import choices


# Create your models here.
class Order (models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User_web, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)

    shipping_total = models.DecimalField (default=5000, max_digits=5, decimal_places=1)
    total = models.DecimalField (default=0, max_digits=8,  decimal_places=2)
    created_at = models.DateTimeField (auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
        return shipping_address

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()  

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()    

    def get_total(self):
        return self.cart.total + self.shipping_total

    def update_total(self):
        self.total = self.get_total()  
        self.save()    

def set_order_id (sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total (sender, instance, *args, **kwargs):
    instance.total = instance.get_total()


  

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

Proyecto/Veterianimal/Veterianimal/orders/views.py
from msilib.schema import ListView
from django.shortcuts import render
from django.shortcuts import redirect
from carts.models import Cart
from .models import ShippingAddress
from .utils import destroy_order
from carts.utils import destroy_cart
from django.shortcuts import get_object_or_404
from pyexpat.errors import messages
from shipping_addresses.views import ShippingAddressListView
from .utils import get_or_create_order
from carts.utils import get_or_create_cart
from django.contrib.auth.decorators import login_required
from .mails import Mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()

# Create your views here.
@login_required(login_url='login')
def order(request):
    cart = get_or_create_cart (request)
    order = get_or_create_order(cart, request)

    return render (request, 'orders/order.html', {
        'cart': cart, 
        'order': order,
    })
@login_required(login_url='login')
def address(request):

    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.shippingaddress_set.all()

    return render(request, 'orders/address.html', {
        'cart': cart,
        'shipping_address': shipping_address,
        'order': order,
        'can_choose_address': can_choose_address
    }) 

@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.addresses

    return render(request, 'orders/select_address.html', {
        'shipping_addresses': shipping_addresses
    })

def check_address(request, pk):
    cart = get_or_create_cart (request)
    order = get_or_create_order(cart, request)

    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)

    return redirect('orders:address')


@login_required(login_url='login')
def confirm(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)
    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/snippets/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address
    })

@login_required(login_url='login')
def cancel(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()

    destroy_cart(request)
    destroy_order(request)

    return redirect ('product')

    

@login_required(login_url='login')
def complete(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.complete()
    Mail.send_complete_order(order, request.user)

    destroy_cart(request)
    destroy_order(request)

    #messages.success(request, 'Compra completada exitosamente')
    return redirect ('index')

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/address.html
{% extends 'base_lo.html' %}

{% block content %}
    <div class="container">
        <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
            <a href="{% url 'orders:order' %}" class="stext-109 cl8 hov-cl1 trans-04">
                Productos
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a href="{% url 'orders:address' %}" class="stext-109 cl8 hov-cl1 trans-04">
                Dirección
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a class="stext-109 cl8 hov-cl1 trans-04">
                Pago
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>
            
            <a class="stext-109 cl8 hov-cl1 trans-04">
                Confirmación
            </a>

        </div>
    </div>
    <div class='col'>
        {% if shipping_address %}
            <section class="address-content">
                <div class="content-address">
                    <form>
                        
                        <div class="form-group">
                            <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>Verifica tu dirección</h3>
                            <div class="h3">
                                Recoge tu pedido en el punto de entrega
                            </div>
                        </div>
                        <div class="form-group btn-container">
                           {% include 'shipping_addresses/snippets/shipping_address.html' %}
                           {% if can_choose_address %}
                            <a href="{% url 'orders:select_address' %}">Elige una dirección</a>
                            
                           {% endif %}

                        </div>
                        <button class="btn btn-primary btn-block mt-3 " ><i class="fa fa-sign-in fa-lg fa-fw"></i>
                            <a href="{% url 'orders:confirm' %}">Proceder a Pago</a>
                    </button>
                    </form>
                </div>
            </section>
        {% else %}         
        <section class="address-content">
            <div class="content-address">
                <form>
                    
                    <div class="form-group">
                        <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>Advertencia</h3>
                        <div class="label">
                           Registra una nueva dirección
                        </di    v>
                    </div>
                    <div class="form-group btn-container">
                        {% url 'orders:address' as next_url %}
                        <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}" class="btn btn-primary btn-block2">Nueva Dirección de envío</a>
                    </div>
                </form>
                
            </div>
        </section>
        {% endif %}
    </div>
    
{% endblock  %}

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/order.html
{% extends 'base.html' %}
{% block breadcrumb %}
	{% include 'orders/snippets/breadcrum.html' %}
{% endblock %}
{% block title %}Orden{% endblock %}
{% load static %}
{% block css%}
	<link rel="stylesheet" href="{% static 'css/orden.css' %}">
{% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/orden.css' %}">
<!-- Latest compiled and minified CSS -->
<script type="text/javascript" src="js/jquery-1.12.3.js"></script>
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
	integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
	crossorigin="anonymous">
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
	integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
	crossorigin="anonymous"></script>

<header>
    <div class="container">
        <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
            <span class="stext-109 cl4">
                Productos
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </span>

            <a href="{% url 'orders:address' %}" class="stext-109 cl8 hov-cl1 trans-04">
                Dirección
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a class="stext-109 cl8 hov-cl1 trans-04">
                Pago
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>
            
            <a class="stext-109 cl8 hov-cl1 trans-04">
                Confirmación
            </a>

        </div>
    </div>
<div class="container mt-4">
	<!-- Orden de compra -->
	<div id="ordenCompra">
			<div class="container">
					<div class="col-xs-3 col-md-3">
						<img src="{% static 'imagenes/Veterianimal.png' %}" alt="IMG-LOGO" width="230px" height="230px">
					</div>
						<h4><b>Datos de usuario</b></h4>
					<div class="mt-3">
						<p id="id_orden"><b>Orden de compra #:</b> 1</p>
						<p id="fecha"><b>Fecha:</b> 31/03/2022</p>
						<p><b>Comprador:</b> {{ user.username }} </p>
						<p><b>Ciudad:</b> Bogotá D.C.</p>
					</div>

				</div>
			</div>
				<div class="col-xs-10 col-md-10 ml-4">
					<h4><b> VETERINARIA A&D Y SPA CANINO</b></h4>
				</div>
			<div class="container" id="datosPRoveedor">
				<div class="col-xs-12 col-md-12 mb-4">

					<div class="mt-2">
						<p><b>Datos del proveedor</b></p>
					</div>

					<p id ="nombre_proveedor"><b>Nombre:</b> Héctor David Hernández García </p>
					<p><b>Dirección:</b>Cll 64 # 23 A 10 Sur <br>
					<p id ="telefono"><b>Telefono:</b> (601)7820524</p>
					<p id="email"><b>Email:</b> vetrinarioayd@gmail.com</p>

				</div>
			</div>

			<div class = "col">
					<div class="card ml-4">
						{% for product in cart.products.all %}
							{%include 'orders/snippets/product.html' %}
						{% endfor %}
					</div>
					<div class="col mb-4">
						{% url 'orders:address' as next_url %}
						{% include 'orders/snippets/resume.html' with next_url=next_url %}
						
					</div>
			</div>

	</div>
</header>
{% endblock %}

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/orders.html
{% extends 'base.html' %}
<br><br>
{% block content %}
    <div class="col mt-5">
        <h4 class="mtext-109 cl2 p-b-30 ">
            <br>
            <br>
            <center>PEDIDOS RECIENTES</center>
        </h4>
        <div class="">
            {% for order in object_list %}
            {% include 'orders/snippets/order.html' %}
            {% endfor %}
        </div>
    </div>


   <br><br><br> 


{% endblock %}    

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/select_address.html
{% extends 'base_lo.html' %}

{% block content %}
    <div class="container">
        <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
            <a href="{% url 'orders:order' %}" class="stext-109 cl8 hov-cl1 trans-04">
                Productos
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a href="{% url 'orders:address' %}" class="stext-109 cl8 hov-cl1 trans-04">
                Dirección
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a class="stext-109 cl8 hov-cl1 trans-04">
                Pago
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>
            
            <a class="stext-109 cl8 hov-cl1 trans-04">
                Confirmación
            </a>

        </div>
    </div>

    <section class="bg0 p-t-23 p-b-140 mt-5">
        <div class="container">
            <div class="p-b-10">
                <h3 class="ltext-103 cl5 mt-5">
                    Selecciona una direccíon de envío
                </h3>
            </div>
            <div class="mt-2">
                {% for shipping_address in shipping_addresses %}
                    <div class="card mb-2">
                       <div class="card-body">
                            <h5 class="card-title"> {{ shipping_address.address }} </h5>
                            <p class="card-title">{{ shipping_address.line1 }} - {{ shipping_address.line1 }} </p>
                            <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">
                                Seleccionar 
                            </a>
                       </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>


{% endblock  %}