Proyecto/Veterianimal/Veterianimal/Veterianimal/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from rating.views import rating
from products.views import ProductListView, IndexListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('contact/', views.contact, name='contact'),
    path('', IndexListView.as_view(), name='index'),
    path('users/rating/', rating, name='rating'),
    path('products/product/', ProductListView.as_view(), name='product'),
    path('users/product_history', views.product_history, name='history_product'),
    path('users/page-user/', views.user, name='user'),
    path('users/register/', views.registrar_usuario, name='registrar'),
    path('cart/', include('carts.urls')),
    path('product-detail/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls'))
]#llaves

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

Proyecto/Veterianimal/Veterianimal/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

Proyecto/Veterianimal/Veterianimal/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion/', views.address, name='address'),
    path('sleccionar/direccion/', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion/', views.confirm, name='confirm'),
    path('cancelar/', views.cancel, name='cancel'),
    path('completar/', views.complete, name='complete'),
    path('completados/', views.OrderListView.as_view(), name='completeds')
]

Proyecto/Veterianimal/Veterianimal/shipping_addresses/urls.py
from stat import S_ENFMT
from django.urls import path

from . import views

app_name = "shipping_addresses"

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateview.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteview.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

Proyecto/Veterianimal/Veterianimal/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<pk:slug>/', views.UserDetailView.as_view(), name='user'), 
]

Proyecto/Veterianimal/Veterianimal/products/models.py
from unicodedata import category
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
#from carts.models import ShopingCart
from modelos.models import Trademarks
from categories.models import Category
# Create your models here.

class Product(models.Model):
    code = models.CharField(verbose_name='Código', max_length=50)
    stock = models.IntegerField(default=0, verbose_name='Stock')
    descrip= models.TextField(verbose_name='Descripción', max_length=500)
    weight= models.CharField(verbose_name='Peso', max_length=10, null=True, blank=True)
    flavor=models.CharField(verbose_name='Sabor', max_length=50, null=True, blank=True)
    price = models.DecimalField(verbose_name='Precio', max_digits=10, decimal_places=2)
    name = models.CharField(verbose_name='Nombre', max_length=60)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='Veterianimal/static/imagenes', null=False, blank=False)
    trademarks = models.ManyToManyField (Trademarks, blank=True)
    category = models.ManyToManyField (Category)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


def set_slug(sender, instance, *args, **kwargs): #callback
    if instance.name and not instance.slug:
        slug = slugify(instance.name)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.name, str(uuid.uuid4())[:8])
            )
        #es objeto unico universal que genera ids aleatoreos
        instance.slug = slug

pre_save.connect(set_slug, sender=Product) 

Proyecto/Veterianimal/Veterianimal/templates/base.html
{% load static %}
<html>
    <head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>
	
		<link rel="icon" type="image/png" href="{% static 'imagenes/Veterianimal.png' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
		
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/MagnificPopup/magnific-popup.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
	
		<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>
    <body>
        {% include 'navbar.html' %}

         {% block index %}
         {% endblock  %}

		 {% block product %}
         {% endblock  %}
        
		 {% block contact %}
         {% endblock  %}
 
		 {% block cart %}
         {% endblock  %}

		 {% block detail %}
         {% endblock  %}
		 
		 {% block address %}
         {% endblock  %}

		 {% block content %}
         {% endblock  %}
 
		 

	<!-- Pie de Pagina -->
	<footer class="bg3 p-t-75 p-b-32">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Categorias
					</h4>

					<ul>
						<li class="p-b-10">
							<a href="{% url 'comida' %}" class="stext-107 cl7 hov-cl1 trans-04">
								Comida
							</a>
						</li>

						<li class="p-b-10">
							<a href="{% url 'servicio' %}" class="stext-107 cl7 hov-cl1 trans-04">
								Servicios Veterinarios
							</a>
						</li>

						<li class="p-b-10">
							<a href="{% url 'accesorio' %}" class="stext-107 cl7 hov-cl1 trans-04">
								Acessorios
							</a>
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Ayuda
					</h4>

					<ul>
						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Orden pedido
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								FAQs
							</a>
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Sobre Nosotros
					</h4>

					<p class="stext-107 cl7 size-201">
						¿Dónde nos encontramos? ¡Fácil! Nuestra dirección esta ubicada en
						<b>
							 Ciudad Bolivar Calle 64 #23A - 10 <br> 
						</b>
						¡Aquí te estamos esperando!
					</p>

					<div class="p-t-27">
						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-instagram"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-pinterest-p"></i>
						</a>
					</div>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Tienes Alguna Duda? <br> Contactanos
					</h4>

					<form>
						<div class="wrap-input1 w-full p-b-4">
							<input class="input1 bg-none plh1 stext-107 cl7" type="text" name="email"
								placeholder="email@example.com">
							<div class="focus-input1 trans-04"></div>
						</div>

						<div class="p-t-18">
							<button class="flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04">
								Enviar
							</button>
						</div>
					</form>
				</div>
			</div>

			<div class="p-t-40">
				<div class="flex-c-m flex-w p-b-18">
					<a href="#" class="m-all-1">
						<img src="{% static 'imagenes/icons/icon-pay-01.png' %}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'imagenes/icons/icon-pay-02.png' %}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'imagenes/icons/icon-pay-03.png' %}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'imagenes/icons/icon-pay-04.png' %}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'imagenes/icons/icon-pay-05.png' %}" alt="ICON-PAY">
					</a>
				</div>

			</div>
		</div>
	</footer>


	<!-- volver al header -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>


	<!-- imagenes de vista previa del producto -->

    </body>
<!--===============================================================================================-->	
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/slick/slick.min.js' %}"></script>
	<script src="{% static 'js/slick-custom.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/parallax100/parallax100.js' %}"></script>
	<script>
        $('.parallax100').parallax100();
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
	<script>
		$('.gallery-lb').each(function() { // the containers for all your galleries
			$(this).magnificPopup({
		        delegate: 'a', // the selector for gallery item
		        type: 'image',
		        gallery: {
		        	enabled:true
		        },
		        mainClass: 'mfp-fade'
		    });
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/isotope/isotope.pkgd.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/sweetalert/sweetalert.min.js' %}"></script>
	<script>
		$('.js-addwish-b2').on('click', function(e){
			e.preventDefault();
		});

		$('.js-addwish-b2').each(function(){
			var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
			$(this).on('click', function(){
				swal(nameProduct, "Este producto se añadio a tu lista de deseos!", "success");

				$(this).addClass('js-addedwish-b2');
				$(this).off('click');
			});
		});

		$('.js-addwish-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

			$(this).on('click', function(){
				swal(nameProduct, "Este producto se añadio a tu lista de deseos!", "success");

				$(this).addClass('js-addedwish-detail');
				$(this).off('click');
			});
		});

		/*---------------------------------------------*/

		$('.js-addcart-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
			$(this).on('click', function(){
				swal(nameProduct, "Se añadio al carro!", "success");
			});
		});
	
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
	<script>
		$('.js-pscroll').each(function(){
			$(this).css('position','relative');
			$(this).css('overflow','hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function(){
				ps.update();
			})
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</html>

Proyecto/Veterianimal/Veterianimal/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block contact%}
	<!-- Content page -->
	<section class="bg0 p-t-104 p-b-116">
		<div class="container">
			<div class="flex-w flex-tr">
				<div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
					<form>
						<h4 class="mtext-105 cl2 txt-center p-b-30">
							Envianos un mensaje
						</h4>

						<div class="bor8 m-b-20 how-pos4-parent">
							<input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Tu correo electronico">
							<img class="how-pos4 pointer-none" src="{% static 'imagenes/icons/icon-email.png' %}" alt="ICON">
						</div>

						<div class="bor8 m-b-30">
							<textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" name="msg" placeholder="¿En qué podemos ayudarte?"></textarea>
						</div>

						<button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
							Enviar
						</button>
					</form>
				</div>

				<div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-map-marker"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Dirección
							</span>

							<p class="stext-115 cl6 size-213 p-t-18">
								Spa Canino A&D Cll 64 n 23 A 10 sur Ciudad Bolivar
							</p>
						</div>
					</div>

					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-phone-handset"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								¡Contactanos!
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								(601)7820524
							</p>
						</div>
					</div>

					<div class="flex-w w-full">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-envelope"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Soporte de Ventas
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								vetrinarioayd@gmail.com
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>	
	<!-- Map -->
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d497.14311729248544!2d-74.14825088531951!3d4.567960700000006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3f9f6aa50ef0e9%3A0x932a501dada24c02!2sVETERINARIA%20AD%20Y%20SPA%20CANINO!5e0!3m2!1ses!2sco!4v1648136112492!5m2!1ses!2sco" width="1349" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
	</div>
{% endblock  %}

Proyecto/Veterianimal/Veterianimal/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Index{% endblock %}
{% block index %}
<!-- Slider -->
	<section class="section-slide">
		<div class="wrap-slick1">
			{% include 'snippets/slider.html' %}
		</div>
	</section>


	<!-- Banner -->
	<div class="sec-banner bg0 p-t-80 p-b-50">
		<div class="container">
			<div class="row">
				{% include 'products/snippets/categories.html' %}
			</div>
		</div>
	</div>
	<!-- Productos -->
	<section class="bg0 p-t-23 p-b-140">
		<div class="container">
			<h3 class="ltext-103 cl5">
					Algunos Productos Recomendados
				</h3>
			</div>


			<div class="row isotope-grid">

			{% for product in product_list %}
			<div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item men">
				<!-- Block2 -->
				<div class="block2">
					<div class="block2-pic hov-img0">
						{% if product.image %}
						<img src="{{product.image.url}}" alt="IMG-PRODUCT">
						{% endif %}
						<a href="{% url 'detail' product.slug %}" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
							Ver
						</a>
					</div>

					<div class="block2-txt flex-w flex-t p-t-14">
						<div class="block2-txt-child1 flex-col-l ">
							<a class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
								{{product.name}}
							</a>

							<span class="stext-105 cl3">
								${{product.price}}
							</span>
						</div>

						<div class="block2-txt-child2 flex-r p-t-3">
							<a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
								<img class="icon-heart1 dis-block trans-04" src="{% static 'imagenes/icons/icon-heart-01.png' %}" alt="ICON">
								<img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'imagenes/icons/icon-heart-02.png' %}" alt="ICON">
							</a>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
{% endblock  %}




	
    

Proyecto/Veterianimal/Veterianimal/templates/navbar.html
{% load static %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
<header>
    <!-- Header desktop -->
    <div class="container-menu-desktop">
        <!-- Topbar -->
        <div class="top-bar">
            <div class="content-topbar flex-sb-m h-full container">
                <div class="left-top-bar">
                    Bienvenido a Veterianimal
                </div>
        </div>

        <div class="wrap-menu-desktop">
            <nav class="limiter-menu-desktop container">
            {% if user.is_authenticated %}
             <!-- Logo desktop -->		
             <a href="#" class="logo">
                <img src="{% static 'imagenes/logodefinitivo.png' %}" alt="IMG-LOGO">
            </a>
                <div class="menu-desktop">
                    <ul class="main-menu">
                        <li class="active-menu">
                            <a href="{% url 'index' %}">Inicio</a>
                        </li>

                        <li>
                            <a href="{% url 'user' %}">Perfil</a>
                        </li>

                        <li class="{% if request.path == cart %}active{% endif %}">
                            <a href="{% url 'product' %}">Tienda</a>
                        </li>

                        <li>
                            <a href="{% url 'contact' %}">Contacto</a>
                        </li>

                        <li>
                            <a href="{{ cart }}"> Mi carrito</a>
                        </li>

                        <li class= " nav-item {% if request.path == completeds %}active{% endif %}">
                            <a href="{{ completeds }}">Mis pedidos</a>
                        </li>


                        <li class="{% if request.path == shipping_addresses %}active{% endif %}">
                            <a href="{{shipping_addresses}}">Direcciones</a>
                        </li>

                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                
                    </ul>
                </div>	
                
                <div class="wrap-icon-header flex-w flex-r-m">
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
                        <i class="zmdi zmdi-search"></i>
                    </div>

                    <!--{% include 'snippets/icon.html' %}-->


                </div>

                <div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
                    <div class="container-search-header">
                        <button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
                            <img src="{% static 'imagenes/icons/icon-close2.png' %}" alt="CLOSE">
                        </button>
            
                        {% include 'products/snippets/search.html' %}
            
                    </div>
                </div> 

               {% else %}

                <!-- Logo desktop -->		
                <a href="#" class="logo">
                    <img src="{% static 'imagenes/logodefinitivo.png' %}" alt="IMG-LOGO">
                </a>

                <!-- Menu desktop -->
                <div class="menu-desktop">
                    <ul class="main-menu">
                        <li class="active-menu">
                            <a href="{% url 'index' %}">Inicio</a>
                        </li>

                        <li>
                            <a href="{% url 'product' %}">Tienda</a>
                        </li>

                        <li>
                            <a href="{% url 'carts:cart' %}">Carrito</a>
                        </li>

                        <li>
                            <a href="{% url 'contact' %}">Contacto</a>
                        </li>

                        <li>
                            <a href="{% url 'registrar' %}">Registrarme</a>
                        </li>
                    
                        <li>
                        <a href="{% url 'login' %}" >Iniciar Sesión</a>
                        </li>
                    </ul>
                </div>	

                <!-- Icon header -->
                <div class="wrap-icon-header flex-w flex-r-m">
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
                        <i class="zmdi zmdi-search"></i>
                    </div>

                </div>
            {%endif%}
            </nav>
        </div>	
    </div>

    
    <!-- Modal Search -->
    <div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
        <div class="container-search-header">
            <button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
                <img src="{% static 'imagenes/icons/icon-close2.png' %}" alt="CLOSE">
            </button>

            {% include 'products/snippets/search.html' %}

        </div>
    </div>

    	<!-- Cart
	<div class="wrap-header-cart js-panel-cart">
		{% include 'snippets/cart_pag.html' %}
	</div>
 -->
    
</header>