Proyecto/Veterianimal/Veterianimal/Veterianimal/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from rating.views import rating
from products.views import ProductListView, IndexListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('contact/', views.contact, name='contact'),
    path('', IndexListView.as_view(), name='index'),
    path('users/rating/', rating, name='rating'),
    path('products/product/', ProductListView.as_view(), name='product'),
    path('users/product_history', views.product_history, name='history_product'),
    path('users/page-user/', views.user, name='user'),
    path('users/register/', views.registrar_usuario, name='registrar'),
    path('cart/', include('carts.urls')),
    path('product-detail/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls'))
]#llaves

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

Proyecto/Veterianimal/Veterianimal/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion/', views.address, name='address'),
    path('sleccionar/direccion/', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion/', views.confirm, name='confirm'),
    path('cancelar/', views.cancel, name='cancel'),
    path('completar/', views.complete, name='complete'),
    path('completados/', views.OrderListView.as_view(), name='completeds')
]

Proyecto/Veterianimal/Veterianimal/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('comida', views.ProductcomidaListView.as_view(), name='comida'),
    path('servicio', views.ProductServListView.as_view(), name='servicio'),
    path('accesorio', views.ProductAcceListView.as_view(), name='accesorio'),
    path('<slug:slug>', views.ProducDetailView.as_view(), name='detail' ),
    
]

Proyecto/Veterianimal/Veterianimal/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<pk:slug>/', views.UserDetailView.as_view(), name='user'), 
]

Proyecto/Veterianimal/Veterianimal/orders/models.py
from django.db import models
from enum import Enum
import uuid
from django.db.models.signals import pre_save
from user.models import User_web
from carts.models import Cart
from shipping_addresses.models import ShippingAddress

from .common import OrderStatus
from .common import choices


# Create your models here.
class Order (models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User_web, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)

    shipping_total = models.DecimalField (default=5000, max_digits=5, decimal_places=1)
    total = models.DecimalField (default=0, max_digits=8,  decimal_places=2)
    created_at = models.DateTimeField (auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id

    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
        return shipping_address

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()  

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()    

    def get_total(self):
        return self.cart.total + self.shipping_total

    def update_total(self):
        self.total = self.get_total()  
        self.save()    

def set_order_id (sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total (sender, instance, *args, **kwargs):
    instance.total = instance.get_total()


  

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

Proyecto/Veterianimal/Veterianimal/products/models.py
from unicodedata import category
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
#from carts.models import ShopingCart
from modelos.models import Trademarks
from categories.models import Category
# Create your models here.

class Product(models.Model):
    code = models.CharField(verbose_name='Código', max_length=50)
    stock = models.IntegerField(default=0, verbose_name='Stock')
    descrip= models.TextField(verbose_name='Descripción', max_length=500)
    weight= models.CharField(verbose_name='Peso', max_length=10, null=True, blank=True)
    flavor=models.CharField(verbose_name='Sabor', max_length=50, null=True, blank=True)
    price = models.DecimalField(verbose_name='Precio', max_digits=10, decimal_places=2)
    name = models.CharField(verbose_name='Nombre', max_length=60)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='Veterianimal/static/imagenes', null=False, blank=False)
    trademarks = models.ManyToManyField (Trademarks, blank=True)
    category = models.ManyToManyField (Category)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


def set_slug(sender, instance, *args, **kwargs): #callback
    if instance.name and not instance.slug:
        slug = slugify(instance.name)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.name, str(uuid.uuid4())[:8])
            )
        #es objeto unico universal que genera ids aleatoreos
        instance.slug = slug

pre_save.connect(set_slug, sender=Product) 

Proyecto/Veterianimal/Veterianimal/orders/views.py
from msilib.schema import ListView
from django.shortcuts import render
from django.shortcuts import redirect
from carts.models import Cart
from .models import ShippingAddress
from .utils import destroy_order
from carts.utils import destroy_cart
from django.shortcuts import get_object_or_404
from pyexpat.errors import messages
from shipping_addresses.views import ShippingAddressListView
from .utils import get_or_create_order
from carts.utils import get_or_create_cart
from django.contrib.auth.decorators import login_required
from .mails import Mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()

# Create your views here.
@login_required(login_url='login')
def order(request):
    cart = get_or_create_cart (request)
    order = get_or_create_order(cart, request)

    return render (request, 'orders/order.html', {
        'cart': cart, 
        'order': order,
    })
@login_required(login_url='login')
def address(request):

    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.shippingaddress_set.all()

    return render(request, 'orders/address.html', {
        'cart': cart,
        'shipping_address': shipping_address,
        'order': order,
        'can_choose_address': can_choose_address
    }) 

@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.addresses

    return render(request, 'orders/select_address.html', {
        'shipping_addresses': shipping_addresses
    })

def check_address(request, pk):
    cart = get_or_create_cart (request)
    order = get_or_create_order(cart, request)

    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)

    return redirect('orders:address')


@login_required(login_url='login')
def confirm(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)
    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/snippets/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address
    })

@login_required(login_url='login')
def cancel(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()

    destroy_cart(request)
    destroy_order(request)

    return redirect ('product')

    

@login_required(login_url='login')
def complete(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.complete()
    Mail.send_complete_order(order, request.user)

    destroy_cart(request)
    destroy_order(request)

    #messages.success(request, 'Compra completada exitosamente')
    return redirect ('index')

Proyecto/Veterianimal/Veterianimal/products/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render
from .models import Product
from categories.models import Category
from django.db.models import Q

# Create your views here.
class ProductListView(ListView):
    template_name= 'products/product.html'

    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        print(context)
        return context

class IndexListView(ListView):
    template_name= 'index.html'

    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 

        return context

class ProducDetailView(DetailView):
    model = Product
 
    template_name = 'products/product-detail.html'

    def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          
          print(context)

          return context


class ProductSearchListView(ListView):

    template_name = 'products/search.html'

    def get_queryset(self):
        filters = Q(name__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
         return self.request.GET.get('q')  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context     

class ProductcomidaListView(ListView):
    
    template_name = 'products/product_com.html'

    def get_queryset(self):
        filter = Q(category__title__icontains="Comida")
        return Product.objects.filter(filter)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['products'] = context['product_list']
        context['count'] = context['product_list'].count()

        return context 

class ProductServListView(ListView):
    
    template_name = 'products/product_ser.html'

    def get_queryset(self):
        filter = Q(category__title__icontains="Juguetes")
        return Product.objects.filter(filter)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['products'] = context['product_list']
        context['count'] = context['product_list'].count()

        return context         

class ProductAcceListView(ListView):
    
    template_name = 'products/product_acce.html'

    def get_queryset(self):
        filter = Q(category__title__icontains="Accesorios")
        return Product.objects.filter(filter)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['products'] = context['product_list']
        context['count'] = context['product_list'].count()

        return context         

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/snippets/confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="col-8 ml-5 mt-5">
    <h4 class="mtext-109 cl2 p-b-30 ">
        <br>
        <br>
        <center>Confirma tu pedido</center>
    </h4>

    <div class="card ml-5">
      <div class="card-body">
            <div class="row">

                <div class="col-4">

                    <div class="font-weight-bold">
                        Dirección de envío
                    </div>

                    <div class="card-text">
                        {{ shipping_address.address }}
                        
                        <div class="card-text">
                            {{ shipping_address.line1 }}
                        </div>
        
                        <div class="card-text">
                            {{ shipping_address.line2 }}
                        </div>
        
                        <div class="card-text">
                            {{ shipping_address.city }}
                        </div>
                    </div>

                </div>



                <div class="col-4">

                    <div class="font-weight-bold">
                        Método de pago
                    </div>
                    <div>
                        Tarjeta terminación
                    </div>

                </div>

                <div class="col-4">


                </div>
                
            </div>
     </div> 
</div>
    <div class="mt-3 ml-5">

        <div class="card">
            
        <div class="card-body">
            {% for product in cart.products.all %}
                {% include 'orders/snippets/product.html'%}
            {% endfor %}
        </div>

        </div>
    </div>

    <div class="col">

    </div>
</div>
<div class="ml-5 mb-2 mt-2">
    <div class="col-8 ml-5 mb-4">
    {% url 'orders:complete' as next_url%}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
    
    <div class="mt-2 mb-3">

        <center><a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar orden</a></center>
    </div>
</div>
</div>


{% endblock %}

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/snippets/order.html
{% load product_extras %}
<div class="card mb-2">
    <div class="card-header">
        <div class="row">

            <div class="col">
                <div class="text-uppercase">   
                    <b>Pedido Realizado</b>
                </div>
                <div class="">
                    {{ order.created_at }}
                </div>
            </div>

            <div class="col-4">
                <div class="text-uppercase">   
                   <b> Total </b>
                    <div class="">
                        {{ order.total | price_format }} COP
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="text-uppercase">
                    <b>Envíado a</b>
                </div>
                <div class="">
                    {{ order.shipping_address }}
                </div>
            </div>
        </div>

    </div>
    <div class="card-body">
        {% for cp in order.cart.products_related %}
        {% with product=cp.product %}
            <div class="row">
                <div class="col-4 ">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="" width="130"  height="110">
                    {% endif %}
                </div>

                <div class="col-4">
                    <div>
                        <b><a href="{% url 'product'%}">{{ product.name }}</a></b>
                    </div>

                    <div class="text-danger">
                       <b>{{ product.price | price_format }}COP</b>
                    </div>

                </div>

                <div class="col-4">
                    <div>
                        <b>Cantidad</b>
                    </div>

                    <div>
                        {{ cp.quantity }}
                    </div>

                </div>
            </div>
        {% endwith %}
        {% endfor %}
    </div>
</div>

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/snippets/product.html
{% load product_extras %}
<div class="row mt-4" >
 <div class="col-2 ml-5 mb-4">
    {% if product.image %}

        <img src="{{ product.image.url }}" alt="Imagen del producto" width="=60" height="90">

    {% endif %}
 </div>
<div class="col ml-2 ">
    <div class="mt-1">
        <strong>
            <a href="{% url 'product'%}">{{ product.name }}</a>
        </strong>
    </div>
    <div class="row ml-3">
        <strong class=" mt-4">{{product.price | price_format }}</strong>
    </div>
</div>
</div>

Proyecto/Veterianimal/Veterianimal/orders/templates/orders/snippets/resume.html
{% load product_extras %}
<div class="">

        <div class="card mt-4">
            <h4><b><center>Resumen del pedido</center></b></h4>
        </div>

        <div class="">
            <div class="card">
                <tbody>
                    <div class="mt-2 ml-3 mb-2">
                        <tr>
                            <td>Productos: </td>
                            <td>{{ cart.total | price_format}}</td>
                        </tr>
                    </div>
                    <div class="mt-2 ml-3 mb-2">
                        <tr>
                            <td>Envío: </td>
                            <td>{{ order.shipping_total | price_format}}</td>
                        </tr>
                    </div>
                </tbody>
            </div>
            <div class="card font-weight-bold ">
                  <div class="mt-1 ml-2">
                      Total a pagar (Impuestos incluidos):
                  </div>

                <div class="mt-1 ml-3 mb-2">
                    <tr>
                        <td>
                            <b> ({{ order.total | price_format }} COP)</b>
                        </td>
                    </tr>
                </div>

            </div>
                <button class="btn btn-primary btn-block mt-3 " ><i class="fa fa-sign-in fa-lg fa-fw"></i>
                        <a href="{{ next_url }}">Proceder a Pago</a>
                </button>
        </div>
</div>