Proyecto/Veterianimal/Veterianimal/Veterianimal/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from rating.views import rating
from products.views import ProductListView, IndexListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('contact/', views.contact, name='contact'),
    path('', IndexListView.as_view(), name='index'),
    path('users/rating/', rating, name='rating'),
    path('products/product/', ProductListView.as_view(), name='product'),
    path('users/product_history', views.product_history, name='history_product'),
    path('users/page-user/', views.user, name='user'),
    path('users/register/', views.registrar_usuario, name='registrar'),
    path('cart/', include('carts.urls')),
    path('product-detail/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls'))
]#llaves

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

Proyecto/Veterianimal/Veterianimal/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

Proyecto/Veterianimal/Veterianimal/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<pk:slug>/', views.UserDetailView.as_view(), name='user'), 
]

Proyecto/Veterianimal/Veterianimal/carts/models.py
import decimal
import uuid
from django.db import models
from Veterianimal import settings 
from products.models import Product
from orders.common import OrderStatus
from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed

class Cart (models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    create_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05
    
    def __str__(self):
        return self.cart_id
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        order = self.order_set.first()
        if order:
            order.update_total()


    def update_subtotal(self):
        self.subtotal = sum([ 
            cp.quantity * cp.product.price for cp in self.products_related()
         ])   
        self.save()  
    

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')

    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()

    class Meta:
        verbose_name = 'Carrito de compra'
        verbose_name_plural = 'Carrito de compras'
        db_table = "Carrito_de_compra"
        ordering = ['id']


class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
      object, created =  self.get_or_create(cart=cart, product=product)

      if not created:
            quantity = object.quantity + quantity

      object.update_quantity(quantity)
      return object


class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save() 

def set_cart_id(sender, instance,*args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

Proyecto/Veterianimal/Veterianimal/carts/views.py
from products.models import Product
from .models import CartProducts
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from .utils import get_or_create_cart 

# Create your views here.
def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html',{
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = Product.objects.get(pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)

    return render(request, 'carts/add.html', {
        'product': product,
        'quantity': quantity,
        'cart_product': cart_product 
    })

def remove(request):   
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('carts:cart') 

Proyecto/Veterianimal/Veterianimal/carts/templates/snippets/add.html
<form action="{% url 'carts:add' %}" method="POST">
  {% csrf_token %}  
  <input type="hidden" name="product_id" value="{{ product.id }}">
    <div class="wrap-num-product flex-w m-l-auto m-r-0" id="remove">
      <button type="button" class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
        <i class="fs-16 zmdi zmdi-minus"></i>
      </button>

      <input class="mtext-104 cl3 txt-center num-product" type="number" id="quantity" name="quantity" value="1" readonly>

      <button type="button" class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m" id="add">
        <i class="fs-16 zmdi zmdi-plus"></i>
      </button>
    </div>

  
  <button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
		Añadir al carrito
	</button>
</form>
<script>
  const add = document.getElementById('add')
  const remove = document.getElementById('remove')
  const quantity = document.getElementById('quantity')

  add.addEventListener('click', function () {
    value = parseInt(quantity.value)
  })

  remove.addEventListener('click', function () {
    value = parseInt(quantity.value)

  })

</script>

Proyecto/Veterianimal/Veterianimal/carts/templates/snippets/cart_pag.html
{% load static %}
{% load product_extras %}
<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Tu Carrito
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
            	
			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
                {% if cart.products.exists %}
                    {% for cp in cart.products_related %}
                        {% with product=cp.product %}
					    <li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
                            {% if product.image %}
							<img src="{{ product.image.url }}" alt="IMG">
                            {% endif %}
                        </div>

						<div class="header-cart-item-txt p-t-8">
							<a href="{% url 'detail' product.slug %}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								{{product.name}}
							</a>

							<span class="header-cart-item-info">
								{{ cp.quantity }}  {{ product.price | price_format }}
							</span>
						</div>
					</li>
                        {% endwith %}
                    {% endfor %}
                {% else %}
                    <li class="header-cart-item flex-w flex-t m-b-12">
                    <div class="header-cart-item-img">
                        
                    </div>

                    <div class="header-cart-item-txt p-t-8">
                            <a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
                           
                            </a>

                            <span class="header-cart-item-info">
                           
                         </span>
                        </div>
                    </li>
                {% endif %}
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Subtotal: {{ cart.subtotal }}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{% url 'carts:cart' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							Ver carrito
						</a>
					</div>
				</div>
			</div>
		</div>

Proyecto/Veterianimal/Veterianimal/carts/templates/snippets/icon.html
{% if cart.products.exists %}
<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="{{ cart.products.count }}">
    <i class="zmdi zmdi-shopping-cart"></i>
</div>
{% else %}
<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="">
    <i class="zmdi zmdi-shopping-cart"></i>
</div>
{% endif %}

Proyecto/Veterianimal/Veterianimal/carts/templates/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %}  
    <input type="hidden" name="product_id" value="{{ product.id }}">
      <button type="submit" class="btn btn-link text-danger">
          Eliminar
      </button>
  </form>